allow negative filter on categories
modrinth/knossos pull request #1013
Opened 2023-02-25 20:37 UTC by ItsiAdam

This is a lazy implementation of negative category filtering. I'll happily adjust to satisfy any requirements/feedback.
As far as I can tell, it doesn't break other checkboxes nor cause any type warnings.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/57854334/221378544-6094acf6-d5a0-4d23-ae39-be53fba7c2ad.png">

2023-04-23 17:06 UTC, falseresync commented
What about checkboxes in other parts of the website? For example, in project settings? This has to be a separate component (TristateCheckbox) or a prop to choose between 2 and 3 state modes

I personally don’t see much use in this

2023-04-23 18:48 UTC, Minenash commented
> I personally don’t see much use in this
Do you mean of the feature itself? Because it's *definitely* useful

2023-05-06 15:06 UTC, triphora requested changes
Just echoing what false mentioned here:
> What about checkboxes in other parts of the website? For example, in project settings? This has to be a separate component (TristateCheckbox) or a prop to choose between 2 and 3 state modes

2023-06-11 18:05 UTC, triphora commented
Will close soon if reviews aren't addressed

2023-06-24 22:27 UTC, closed without merging