Add indicators for visibility - replace confusingly worded description on project settings page.
modrinth/knossos pull request #1092
Opened 2023-04-11 15:58 UTC by mineblock11

## Information

Replaces the following text:

> Set the visibility of your project. Listed and archived projects are visible in search. 
Unlisted projects are published, but not visible in search or on user profiles. 
Private projects are only accessible by members of the project.

With some indicators that are much easier to understand.

Potentially could word differently? Not sure if the following should be used instead for the search and member profile bulletpoint

- Visible in search results
- Visible on member profiles

## Screenshots

![](https://i.imgur.com/S1DBP7C.png)
![](https://i.imgur.com/pNA5Z8u.png)

2023-04-11 16:10 UTC, Prospector commented
I don't like how this doesn't tell you what each does until you click on it. You would have to select Unlisted to know what it did, for example. That's not intuitive because you'd want to know what it did before you selected it

2023-04-11 16:17 UTC, mineblock11 commented
Hm. Doesn't the user need to confirm their selection anyways via the "Save changes" button? Currently it's safe to switch between dropdown options without causing the visibility of the project to update.

2023-04-11 16:17 UTC, mineblock11 commented
I forgot to upload a video of it as well:

![](https://i.imgur.com/47Bqp7f.gif)

2023-04-11 16:37 UTC, Prospector commented
Yeah but that's not intuitive to have to switch between options in order to figure out what they do. I think the display you added is fine, I'd just leave the old text (or an improvement upon it) as well.

2023-04-11 17:36 UTC, mineblock11 commented
I've updated it with a better description.

![](https://i.imgur.com/Dye7Bcm.png) 
![](https://i.imgur.com/ONqfh5M.png)

2023-04-11 18:07 UTC, Prospector approved these changes

2023-04-11 18:07 UTC, Prospector commented on pages/[type]/[id]/settings/index.vue
> +    TickIcon,
I would rename this to CheckIcon to be more consistent but otherwise LGTM

2023-04-11 20:41 UTC, Prospector commented
Wait, why is exit.svg even a thing? We use `x.svg` for everything it seems.

2023-04-12 05:54 UTC, Minenash commented
A problem with using a checklist looking system, besides what pro has mentioned, as that it could give the user a false impression of the actual state of the actual visibility (instead of the target visibility).

A possible idea would be to do something similar to the theme selector. Where each entry has information about it. Like it being listed in search/profile, who can see it, any warnings that the status displays

2023-04-12 06:04 UTC, mineblock11 commented
The actual visibility of the project is always listed underneath its name isn't it? I assume with the description above the checklist it would make it obvious that it's the target visibility.

A fix could be renaming it from Visibility -> Target Visibility

2023-04-13 17:08 UTC, Prospector reviewed
removing my approval

2023-04-13 17:08 UTC, Prospector requested changes
why can't you just remove an approval

2023-04-13 21:57 UTC, mineblock11 commented
Should be all good now

2023-04-18 00:59 UTC, triphora reviewed
Might not be worth fixing but there is a ton of unnecessary padding here
![image](https://user-images.githubusercontent.com/60205699/232642011-5c079025-c51d-4b06-b82e-4fc728f4e512.png)

2023-04-18 00:59 UTC, triphora commented on pages/[type]/[id]/settings/index.vue
> +          <span class="label__title">Target Visibility</span>
```suggestion
          <span class="label__title">Target visibility</span>
```

2023-04-18 01:03 UTC, Prospector commented
I don't like the heading "Target visibility". Maybe instead, when your selected visibility is different from the current saved visibility, it changes the text from "Visible in search" to "Will be visible in search" to show that it's unsaved.

2023-04-18 01:03 UTC, Prospector requested changes
I don't like the heading "Target visibility". Maybe instead, when your selected visibility is different from the current saved visibility, it changes the text from "Visible in search" to "Will be visible in search" to show that it's unsaved.

2023-04-18 18:08 UTC, mineblock11 commented
![](https://i.imgur.com/JusR1m9.gif)

2023-04-18 18:08 UTC, Prospector commented
I think that's pretty good!

2023-04-18 18:08 UTC, Prospector commented
Just rename back to Visibility

2023-04-30 16:32 UTC, brawaru commented
I personally don't like text changing like this, but also when thinking about solution I can only remember a couple UIs that show a table (current / new), others instead use a popup that explains consequences (e.g. GitHub), since changing visibility is a bit dangerous action.

![Screenshot of table layout concept showing two cards below the description for visibility option, where first card shows current visibility (not visible in search, nor via profile, and can only be accessed by members through URL) and new visibility (visible in search and on profile, and accessible through URL by everyone. In URL visibility who can view URL is marked with bold text. On the right arrows and square is drown above tho selector, suggesting that it should be moved slightly above.](https://user-images.githubusercontent.com/10401817/235364439-c452bbba-e112-4b95-a16e-f4bcef195827.jpg)

2023-05-01 16:08 UTC, mineblock11 commented
This wouldn't fit on mobile, and I think its quite excessive for something so simple

2023-06-06 21:20 UTC, Geometrically approved these changes

2023-06-06 21:20 UTC, merged