Add "float: right|left" support for css.
modrinth/knossos pull request #1208
Opened 2023-06-17 16:13 UTC by mineblock11

Would be good if this could get into production asap? A few mods need it from a brief search on discord

Fixes #1207

2023-06-17 16:50 UTC, triphora reviewed
Center?

2023-06-17 16:52 UTC, mineblock11 commented
Float does not have a "center" value.

https://developer.mozilla.org/en-US/docs/Web/CSS/float#values

2023-06-17 23:46 UTC, brawaru requested changes
Maybe we should also have `align` attribute for elements which would allow for compatibility with GitHub READMEs? I believe this is just a matter of whitelisting the attribute and browsers already take care of it on their own.

2023-06-17 23:46 UTC, brawaru commented on helpers/parse.js
> +      'float': /^left|right$/,
```suggestion
      float: /^left|right$/,
```

2023-06-18 02:11 UTC, ThatGravyBoat commented
if the `float` is added then `clear` should also be added to make it more compatible

2023-06-20 19:39 UTC, Prospector commented
slightly confused, the linked issue is about align but this PR is about float?

2023-06-21 15:13 UTC, ThatGravyBoat commented
I assume why this does the `float` CSS property instead of adding the `align` attribute is that the `align` attribute is deprecated while the `float` CSS property is not and is the recommended replacement for `align` for images.

2023-06-21 16:14 UTC, brawaru commented
It being deprecated doesn't mean much, it's well supported by the browsers, and if you want to be sure, you can just re-implement it using simple CSS. But allowing it would ensure compatibility with Markdown from GitHub and other platforms.

<details>
<summary>SCSS</summary>

```scss
:not(img) {
  &[align="left"] {
    text-align: left;
  }
  
  &[align="middle"], &[align="center"] {
    text-align: center;
  }
  
  &[align="right"] {
    text-align: right;
  }
}

img {
  &[align="left"] {
    float: left;
    vertical-align: top;
  }
  
  &[align="right"] {
    float: right;
    vertical-align: top;
  }
  
  &[align="top"], &[valign="top"] {
    vertical-align: top;
  }
  
  &[align="middle"], &[valign="middle"] {
    vertical-align: middle;
  }
  
  &[align="bottom"], &[valign="bottom"] {
    vertical-align: bottom;
  }
}
```

(Can be wrapped in `.markdown-body { ... }` so that it only applies to Markdown)

</details>

2023-09-02 13:07 UTC, triphora approved these changes
Removed the linked issue since that's for something different.

2023-09-02 13:32 UTC, merged