Add downloads and follows to Projects list
modrinth/knossos pull request #1346
Opened 2023-08-29 15:41 UTC by joshieman06

![image](https://github.com/modrinth/knossos/assets/71846165/189d99a8-5d53-4a89-add7-e3caccbd9b87)

2023-09-02 13:05 UTC, triphora requested changes
Lint fails, also the dropdown should be fixed width
![image](https://github.com/modrinth/knossos/assets/60205699/9701781b-c25a-4068-9c5a-7517cadca809)

2023-09-02 19:20 UTC, triphora commented on pages/dashboard/projects.vue
> +          })
```suggestion
          sortedArray = projects.slice().sort((a, b) => a.downloads - b.downloads)
```

2023-09-02 19:20 UTC, triphora commented on pages/dashboard/projects.vue
> +          })
```suggestion
          sortedArray = projects.slice().sort((a, b) => a.followers - b.followers)
```

2023-09-02 19:20 UTC, triphora commented on pages/dashboard/projects.vue
> +          })
May not be lint-safe - make sure you still run `pnpm run fix`

2023-09-02 19:23 UTC, triphora commented on pages/dashboard/projects.vue
> +  min-width: 230px;
Avoid px, try 15rem

2023-09-02 19:30 UTC, triphora reviewed
Should probably have a more elegant solution for smaller width screens
![image](https://github.com/modrinth/knossos/assets/60205699/9600c4f9-5866-470b-8792-257c893b2910)

2023-09-24 19:27 UTC, triphora commented
Will soon be closed if above comments are not addressed

2023-09-26 02:52 UTC, joshieman06 commented
School has started back up so I don't have time to engineer a fix for smaller screens. All other problems should be fixed

2024-01-28 23:11 UTC, Prospector commented
Will close for now since mobile support is necessary

2024-01-28 23:11 UTC, closed without merging