Fix: well-known location does not redirect to the change password page
modrinth/knossos pull request #1360
Opened 2023-09-09 16:27 UTC by Mysterious-Dev

All is in the title.

I think we can deploy this PR to test if password manager can use this ^^.

Close #1317

2023-09-09 16:51 UTC, brawaru requested changes
This is not a good way of doing that, since this will be a middleware running for every page. Instead, what you should do, is create a server route with redirect in `/server/routes/.well-known/change-password.ts`. It should be as simple as calling a `sendRedirect` function and returning.

2023-09-10 12:20 UTC, Mysterious-Dev commented
> This is not a good way of doing that, since this will be a middleware running for every page. Instead, what you should do, is create a server route with redirect in `/server/routes/.well-known/change-password.ts`. It should be as simple as calling a `sendRedirect` function and returning.

Done ^^.

2023-09-10 13:59 UTC, brawaru approved these changes
:shipit:

2023-09-10 16:24 UTC, triphora approved these changes

2023-09-10 16:25 UTC, merged