Pats Modal confirm for removal
modrinth/knossos pull request #1375
Opened 2023-09-22 11:56 UTC by Mysterious-Dev

All is in the title ^^.

Close #1272

2023-09-22 13:54 UTC, Mysterious-Dev commented
Now, it's ready for review ^^

2023-09-24 19:36 UTC, triphora requested changes
Looks great, just a spelling issue

2023-09-24 19:36 UTC, triphora commented on pages/settings/pats.vue
> +const deletPatIndex = ref(null)
```suggestion
const deletePatIndex = ref(null)
```

2023-09-24 19:36 UTC, triphora commented on pages/settings/pats.vue
> +              deletPatIndex = pat.id
```suggestion
              deletePatIndex = pat.id
```

2023-09-24 19:36 UTC, triphora commented on pages/settings/pats.vue
> +      @proceed="removePat(deletPatIndex)"
```suggestion
      @proceed="removePat(deletePatIndex)"
```

2023-09-25 06:30 UTC, Mysterious-Dev commented
> Looks great, just a spelling issue

Done ^^.

2023-09-29 02:44 UTC, triphora approved these changes

2023-09-29 02:44 UTC, merged