Move extra loaders to the bottom of the list
modrinth/knossos pull request #1398
Opened 2023-10-05 04:49 UTC by Minenash

Right now, when the user clicks on `More` to show the rest of the loaders, the extra loaders are intermixed with the original. This is unitutive, and makes it harder to find what you're looking for and  to see what loaders are the ones behind the more.

This PR fixes that by putting all the loaders hidden by `More` at the bottom of the list

2023-10-05 06:35 UTC, Prospector requested changes
I feel like the list of uncollapsed loaders should be a constant somewhere instead of repeating them

2023-10-05 06:42 UTC, Minenash commented
I also had that thought. I didn't realize loaders were listed in `composables/tag.js`. The list could be added there

2023-10-05 15:34 UTC, Minenash commented
Should it be a list major loaders, or hidden loaders

2023-10-05 20:58 UTC, Minenash commented on pages/search/[searchProjectType].vue
>                v-for="loader in tags.loaders.filter((x) => {
Oh wait, this for can just be of hiddenModLoaders

2023-10-06 04:07 UTC, Minenash commented
My original plan was just to do  
`:active-filters="header === 'resolutions' ? orFacets : facets"`  
` @toggle="header === 'resolutions' ? toggleOrFacet : toggleFacet` " 

But the toggle one didn't work, so unless there's a way to do it, I ended up duplicating the search filter.

Using orFacets should be safe, since the only other thing that used them was loaders, but you don't have access to loaders on resource packs.

This does mean however that resolutions now use the g instead of f parameter, but that was going to be true anyways

2024-04-14 15:03 UTC, Prospector approved these changes

2024-06-12 02:45 UTC, merged