Fixed Password matching msg showing when confirm is empty
modrinth/knossos pull request #1400
Opened 2023-10-06 00:25 UTC by Minenash

Fixes #1267

2023-10-06 00:31 UTC, Minenash commented
![image](https://github.com/modrinth/knossos/assets/12193049/d494461f-b51c-4dd2-94eb-58c7d4d29818)

On project edit pages, it makes sense putting the validation msgs at the top since there's a lot of fields, and it's nice to see all the msgs in once place. Here, all fields are visible, and only 1 field has a msg. Imo it makes sense to put it next to the field that causing the validation error

2023-10-25 20:35 UTC, triphora approved these changes

2023-10-25 20:43 UTC, Geometrically requested changes
please run lint

2023-10-29 17:17 UTC, Minenash commented
Done

2023-12-22 01:09 UTC, merged