Add align to img, p, and div
modrinth/knossos pull request #1401
Opened 2023-10-06 02:30 UTC by Minenash

Fixes #1207 but also adds it to p and div for better Github Markdown compatibility.

Possible concerns:
- To get the img to not overflow the description/preview box, `overflow: y` was added to `.markdown-body`. I'm not 100% sure this is the best place to add it

2023-10-25 20:34 UTC, triphora requested changes
Please move this over to omorphia, the helpers will soon be replaced with those from there

2023-10-29 16:54 UTC, Minenash commented
I see the place to move the actual additions, but I'm not seeing the file that displays the rendered markdown (since the y overflow needs to be changed for it), unless the MarkdownEditor is also used on the normal project page?

2023-10-31 02:15 UTC, triphora commented
https://github.com/modrinth/omorphia/blob/39a4297168f34207e8fd8fc79abeccd073aacdeb/lib/assets/styles/classes.scss#L836

2024-01-27 17:53 UTC, triphora commented
Closing as helpers/parse.js no longer exists in knossos

2024-01-27 17:53 UTC, closed without merging