Oauth 2 Flow UI
modrinth/knossos pull request #1440
Opened 2023-11-10 05:07 UTC by darling

2023-12-01 21:26 UTC, IMB11 requested changes

2023-12-01 21:26 UTC, IMB11 commented on pages/auth/authorize.vue
> +    const res = await useBaseFetch('auth/oauth/accept', {
This needs to be changed to `oauth/accept` - API route changed.

```suggestion
    const res = await useBaseFetch('oauth/accept', {
```

2023-12-01 21:26 UTC, IMB11 commented on pages/auth/authorize.vue
> +    const res = await useBaseFetch('auth/oauth/reject', {
Same here.

```suggestion
    const res = await useBaseFetch('oauth/reject', {
```

2023-12-01 21:33 UTC, darling commented
@IMB11 Thanks! It seems like those routes changing got stuck in a git stash.

2023-12-05 03:25 UTC, Geometrically approved these changes

2023-12-05 03:26 UTC, merged