Add enter shortcut for 2FA & email management
modrinth/knossos pull request #1504
Opened 2024-01-05 14:25 UTC by Mysterious-Dev

All is in the title ^^.

It's a QOL for account management.

2024-01-07 17:06 UTC, triphora requested changes

2024-01-07 17:06 UTC, triphora commented on pages/settings/account.vue
> +              these codes like your password.
```suggestion
              Download and save these back-up codes in a safe place. You can use these in-place of a
              2FA code if you ever lose access to your device! You should protect these codes like
              your password.
```

2024-01-08 13:30 UTC, Mysterious-Dev commented on pages/settings/account.vue
> +              these codes like your password.
Done ^^.

2024-01-08 20:59 UTC, triphora approved these changes

2024-01-09 15:59 UTC, Prospector approved these changes

2024-01-18 16:56 UTC, merged