Add initial support for the v2 of the API (Still WIP)
modrinth/knossos pull request #250
Opened 2021-05-29 16:23 UTC by Redblueflame

2021-06-06 22:06 UTC, wafflecoffee requested changes
In addition, reports cannot be created for mods:
![image](https://i.imgur.com/ffN5edJ.png)
Reports for versions redirect to the wrong page:
![image](https://i.imgur.com/I4JVk4O.png)
And there is also no visual confirmation that you have indeed submitted a report.

2021-06-08 01:01 UTC, venashial commented
Should I create a PR for this branch to merge [`venashial:dynamic-routes`](/venashial/knossos/tree/dynamic-routes) into [`apiv2-support`](/modrinth/knossos/tree/apiv2-support)? (There shouldn't be any merge conflicts.)

2021-07-16 06:14 UTC, wafflecoffee commented on pages/project/_id.vue
> +            Client mod
```suggestion
            Server mod
```

2021-07-26 00:04 UTC, venashial commented
Despite 59f685c updating this PR with the master branch, some changes weren't merged. (Likely due to project pages and components being copied/moved.) For example, now both #292 and  #252 have conflicting changes to the wording on the project editing page. A manually file comparison between the master branch and this PR could help find these discrepancies.

2021-07-26 03:15 UTC, Prospector commented
Updated all the wording from that PR in my PR

2021-07-26 19:37 UTC, venashial commented
59f685c did less merging than I thought. It appears that the only two commits from master to get merged into this PR since May 29 were:
- be3ed7d3806b18fc200b8249720673bd99de6f2c
- 9b4d58cfe8531ecafeee463b14c45e6e65284e87

All the other (15) commits from master need to be merged into this branch.

2022-01-09 22:19 UTC, merged