Add a roadmap page and prioritize mentioning that revenue is not yet implemented
modrinth/knossos pull request #323
Opened 2021-11-14 18:30 UTC by MarkusG

Adding a roadmap to the site not only makes it more available, but the included link also draws more members into the Discord server.

Also, I'm brand new to Vue.js, so any criticism is, of course, welcome.

2021-11-14 18:34 UTC, wafflecoffee requested changes
It would also be best for this to target the `apiv2-support` branch rather than the `master` branch - apiv2 has the pending redesign and has a lot of pending changes which may end up conflicting with these changes.

2021-11-14 18:34 UTC, wafflecoffee commented on layouts/default.vue
> +                <span>Roadmap</span>
This should preferably be in the footer, not the header.

2021-11-14 22:13 UTC, MarkusG commented
Rebased my changes onto the `apiv2-support` branch, re-styled the roadmap page to match the about page, and also moved the roadmap link from the navbar into the footer.

2021-11-14 22:16 UTC, wafflecoffee approved these changes

2021-11-15 09:07 UTC, falseresync approved these changes

2022-01-09 22:19 UTC, closed without merging

2022-01-09 22:22 UTC, Geometrically commented
Sorry for never reviewing this, if you still want this PR, you can retarget it to master. However, the new homepage will have  a roadmap.