Minor fixes for "See all" button design
modrinth/knossos pull request #627
Opened 2022-08-25 04:43 UTC by Brawaru

- Now uses link colour, link hover color on hover, and active.. when active.
- Change :focus to :focus-visible to avoid link getting stuck in that ‘hovered’ state because focus does not actually change (it deffo should though, something to fix in the future — should be one fragment change).
- Retract all padding, leaving element padded visually, but not causing changes to layout. This is a suprise tool that will help us later.

<table>
  <tr>
    <th>State</th>
    <th>Light mode</th>
    <th>Dark mode</th>
  </tr>
  <tr>
    <td align="center">Normal</td>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/186574775-a7283015-39ea-4a21-bfc2-66368b16bcb7.png" alt="Preview of normal link state in light theme." align="center"></td>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/186574585-4621a05b-1f03-401a-be8f-d1c5ea9cd443.png" alt="Preview of normal link state in dark theme." align="center"></td>
  </tr>
  <tr>
    <td align="center">Hovered</td>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/186574798-5f41fb34-dc59-4be7-a12c-66bf63567b15.png" alt="Preview of hovered link state in light theme." align="center"></td>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/186574638-e738e027-9ab7-47d3-bcfc-e3f1e501bbfa.png" alt="Preview of hovered link state in dark theme." align="center"></td>
  </tr>
    <td align="center">Active</td>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/186574919-a3813cc6-abae-4331-98cf-dd5ffefdec2b.png" alt="Preview of active link state in light theme." align="center"></td>
    <td align="center"><img src="https://user-images.githubusercontent.com/10401817/186574729-6f33fbf0-bde4-481a-9573-9a28a1cc36da.png" alt="Preview of active link state in dark theme." align="center"></td>    
  <tr>
  </tr>
</table>

2022-08-25 05:02 UTC, Geometrically requested changes
I don't think should be the link color. No other button is like that on the site

2022-08-25 05:17 UTC, Brawaru commented
Well, it supposed to be a link. Should I change it back to normal colour (black/white depending on the theme) for normal state or for all states?

2022-08-25 15:13 UTC, wafflecoffee commented
> No other button is like that on the site

Maybe instead we make the other buttons on the site look like that. I think what's here looks a lot better and also makes a lot more sense in terms of accessibility. We could adopt something along the lines of what the rewrite has:
![Peek 2022-08-25 11-12](https://user-images.githubusercontent.com/60205699/186703299-9ac58530-3308-4171-8d44-5b97a5f33ae9.gif)

2022-08-25 15:20 UTC, jadelily18 commented
i like the idea of making it look more the the rewrite. It just looks really clean and easier to read compared to production.

2022-08-25 19:32 UTC, Geometrically commented
> > No other button is like that on the site
> 
> Maybe instead we make the other buttons on the site look like that. I think what's here looks a lot better and also makes a lot more sense in terms of accessibility. We could adopt something along the lines of what the rewrite has: ![Peek 2022-08-25 11-12](https://user-images.githubusercontent.com/60205699/186703299-9ac58530-3308-4171-8d44-5b97a5f33ae9.gif) [ ![Peek 2022-08-25 11-12](https://user-images.githubusercontent.com/60205699/186703299-9ac58530-3308-4171-8d44-5b97a5f33ae9.gif) ](https://user-images.githubusercontent.com/60205699/186703299-9ac58530-3308-4171-8d44-5b97a5f33ae9.gif) [ ](https://user-images.githubusercontent.com/60205699/186703299-9ac58530-3308-4171-8d44-5b97a5f33ae9.gif)

I don't think this is true. If it's styled as a button, it should look like a button. There shouldn't be a button-link hybrid. Even on the rewrite, buttons are never styled with a blue link color.

It should either be a link, which is blue with an underline, or a button with the background, hover, and normal text

2022-09-04 05:34 UTC, Geometrically approved these changes
thanks for the PR and putting up with all my bikeshed :+1:

2022-09-04 05:34 UTC, merged