Migrate to lucide-vue for icons and update copying info
modrinth/knossos pull request #753
Opened 2022-11-19 02:56 UTC by triphora

2022-11-20 06:57 UTC, Prospector commented
I started making a list of icons that I felt looked notably worse than before, but I'm not sure it's worth actually fixing these because just using all lucide would really be quite helpful. The only one I think definitely needs to be changed is the money icon, it's just not recognizable

Note | Current |  Lucide
:-:|-|:-:
Download icon just looks weird and poorly proportioned | ![image](https://user-images.githubusercontent.com/6166773/202889456-f7c83a26-6a56-41d8-bf0f-5549e91073cf.png)  |  ![image](https://user-images.githubusercontent.com/6166773/202889430-3ab8a218-4022-4b07-a142-ed5b2e3d3d37.png)
A bill at this size just looks like a rectangle and not money | ![image](https://user-images.githubusercontent.com/6166773/202889559-c5475706-3ead-4c4b-b02b-31e6e3c5cff6.png) | ![image](https://user-images.githubusercontent.com/6166773/202889554-7df75bf9-8e67-4792-a48d-69eaa289059f.png)
The narrower shoulders on the Account is just less distinct and is just marginally worse | ![image](https://user-images.githubusercontent.com/6166773/202889631-7f4f192d-f84b-4655-8669-12c9aa75d5a6.png) | ![image](https://user-images.githubusercontent.com/6166773/202889675-3290dee7-6b78-4d0e-a9ae-6d6c4c2d0ad8.png)
Project cards use an "Edit" icon instead of an "Updated" icon | ![image](https://user-images.githubusercontent.com/6166773/202889709-10142c4a-e793-457c-b0d3-13edebe38703.png) | ![image](https://user-images.githubusercontent.com/6166773/202889703-0fc02235-c315-4655-ac28-08f17a298016.png)
Search icon looks unbalanced and poorly proportioned | ![image](https://user-images.githubusercontent.com/6166773/202889758-9d15e23a-d5a5-498a-ae82-847fee9d81aa.png) | ![image](https://user-images.githubusercontent.com/6166773/202889770-668dd007-fd4d-402a-806f-196d8c5df30d.png)
New caret doesn't match the font weight as nicely | ![image](https://user-images.githubusercontent.com/6166773/202889838-018b983b-7335-45c9-88b0-71b71ce4693f.png) | ![image](https://user-images.githubusercontent.com/6166773/202889821-b1f2a836-523a-45ce-8ea4-25362f481a23.png)

2022-11-20 06:59 UTC, Prospector requested changes

2022-11-20 06:59 UTC, Prospector commented on pages/dashboard.vue
> +  Banknote as CurrencyIcon,
Use dollar sign instead of bank note

2022-11-20 06:59 UTC, Prospector commented on pages/settings.vue
> +  Banknote as CurrencyIcon,
Use dollar sign instead of bank note

2022-11-20 07:03 UTC, Prospector commented
I actually just noticed this one, without the circle it doesn't even look like the GitHub logo:

![image](https://user-images.githubusercontent.com/6166773/202890107-cd0aac08-f94f-42c9-89d2-fbf5eb6b02da.png)

2022-11-21 02:59 UTC, triphora commented
Closing in favour of #760

2022-11-21 02:59 UTC, closed without merging