Transition between animation states on TextLogo
modrinth/knossos pull request #955
Opened 2023-01-30 08:12 UTC by NeutronicMC

Currently, when a page stops loading, TextLogo immediately ends its animation and reverts to its original state.
This PR allows the animation to finish playing before stopping.

2023-01-30 21:00 UTC, Brawaru requested changes

2023-01-30 21:19 UTC, NeutronicMC commented on components/brand/TextLogo.vue
> +const startTime = ref(0)
Oh yeah, missed that! Was messing around with stuff while debugging. Will fix, thanks!

2023-02-01 01:03 UTC, triphora approved these changes

2023-02-01 18:38 UTC, Geometrically approved these changes

2023-02-01 18:38 UTC, merged