Make project categories link to search for projects in that category, fixes #351
modrinth/knossos pull request #978
Opened 2023-02-02 17:18 UTC by CodeF53

This fixes #351

2023-04-23 17:12 UTC, falseresync approved these changes

2023-04-23 17:13 UTC, triphora requested changes
Please fix merge conflicts

2023-04-23 17:22 UTC, Prospector requested changes
Type needs to be converted using $getProjectTypeForUrl (or whatever it's called) and links should be styled as links, meaning they should lighten on hover/focus and click and get an underline when hovering

2023-06-11 18:04 UTC, triphora commented
Will close soon if reviews aren't addressed

2023-06-19 17:45 UTC, closed without merging