Add tooltips to project statuses
modrinth/knossos pull request #992
Opened 2023-02-11 19:19 UTC by smcmo

Noticed a lot of people asking about what the different statuses meant in the Discord, so I added tooltips that explain what they mean a bit more.

Example:
![image](https://user-images.githubusercontent.com/65502593/218277103-728a5e42-5ef5-4433-a0d5-c3ac8ab754ac.png)

2023-02-11 19:23 UTC, triphora requested changes

2023-02-11 19:23 UTC, triphora commented on components/ui/Badge.vue
> +          'Your project has been withheld from publishing. See the moderation message for more details.'
```suggestion
          'Your project is accessible by link but is not published in search. See the moderation message for more details.'
```

2023-02-11 19:23 UTC, triphora commented on components/ui/Badge.vue
> +      <span> <ArchiveIcon /> Archived </span>
What happened here?

2023-02-11 19:26 UTC, smcmo commented on components/ui/Badge.vue
> +      <span> <ArchiveIcon /> Archived </span>
Oops missed that one

2023-02-11 19:34 UTC, triphora approved these changes

2023-02-23 07:20 UTC, MagnusHJensen commented on components/ui/Badge.vue
> +          'Your project will be automatically published at your chosen time and date.'
```suggestion
          'Your project will be automatically published at the chosen time and date.'
```

"Your" sounds more like it's an initial feature of scheduling, where as "the" sounds more like you have scheduled it.

2023-03-22 20:23 UTC, triphora commented
Sorry for not getting to this sooner, but do you think you could redo this PR on [omorphia](https://github.com/modrinth/omorphia/blob/master/lib/components/base/Badge.vue)? I'm not sure if v-tooltip is working properly there yet, but this component will eventually be deleted in knossos once we convert it to using omorphia.

2023-03-23 03:56 UTC, smcmo commented
I can definitely at least try it out yea

2023-03-23 04:01 UTC, closed without merging